sudo: false
language: node_js
node_js:
  - "0.12"

env:
  global:
    - BROWSER_PROVIDER_READY_FILE=/tmp/sauce-connect-ready
    - LOGS_DIR=/tmp/angular-hint-build/logs
    - SAUCE_USERNAME=angular-ci
    - SAUCE_ACCESS_KEY=9b988f434ff8-fbca-8aa4-4ae3-35442987

install:
  - mkdir -p $LOGS_DIR
  - ./scripts/sauce_connect_setup.sh
  - npm install -g npm
  - npm install
  - ./scripts/wait_for_browser_provider.sh

script:
  - ./scripts/test_on_sauce.sh
